version: "3.8"

services:
  cryptospike-client:
    build: .
    container_name: cryptospike-client
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - cryptospike_data:/app/server/data

volumes:
  cryptospike_data:
    name: cryptospike_data
