version: "3.8"

services:
  client:
    build: .
    container_name: cryptospike-client
    restart: unless-stopped
    volumes:
      - cryptospike_data:/app/server/data

volumes:
  cryptospike_data:
    name: cryptospike_data
